name: EC2 Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Decode private key
      run: echo "${{ secrets.EC2_KEY }}" | base64 --decode > /tmp/private-key.pem
      shell: bash

    - name: Set SSH permissions
      run: chmod 600 /tmp/private-key.pem
      shell: bash

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i /tmp/private-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          docker pull melbehery/edu-city-backend
          docker stop edu-city || true
          docker rm edu-city || true
          docker run -d --name edu-city --env MONGO_URI=${{ secrets.MONGO_URI }} -p 3000:3000 melbehery/edu-city-backend
        EOF
      shell: bash
